name: autosub

on:
  push:
    branches:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      -
        name: build
        run: |
          set -v
          python -m pip install --upgrade pip
          pip install .
          autosub -h

  test:

    runs-on: ubuntu-latest
    needs: build

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      -
        name: build
        run: |
          set -v
          python -m pip install --upgrade pip
          pip install .
          autosub -h

      -
        name: pylint check
        continue-on-error: true
        run: |
          set -v
          pip install pylint
          pylint autosub

      -
        name: prepare test environment
        run: |
          set -v
          sudo apt update
          sudo apt install -qq -y ffmpeg
          pip install -U ffmpeg-normalize langcodes youtube-dl

      -
        name: prepare test file
        run: |
          set -v
          youtube-dl --no-progress -f 134+140 FhPI5lbyz-I -o video.mp4
          ffmpeg -hide_banner -loglevel quiet -nostats -ss 00:02:20 -i video.mp4 -to 00:02:00 test.mp4 && rm video.mp4

      -
        name: test autosub
        timeout-minutes: 10
        run: |
          autosub -i test.mp4 -S en-us -D zh-cn -der -of all
          cat 'test.en-us&zh-cn.srt'

      -
        uses: actions/upload-artifact@v2
        with:
          name: result
          path: test*